### ISSUE TITLE
NullPointerException after install

### ISSUE THREAD

**Issue by JacobHenner** [nongfenqi/nexus3-rundeck-plugin#4]
Hello,

After following the installation instructions in README.md, I get a NullPointerException when starting Nexus. Is it possible that the specified configuration for startup.properties is incorrect? It appears to be in a different format than the other lines in that file.

Regards,
Jacob Henner

**Comment by chenlingmin** [comment]
@JacobHenner Please confirm whether there are any spelling mistakes.

![image](https://user-images.githubusercontent.com/8233283/29455248-0ef5c9b8-8443-11e7-8da7-4127a4ae3b56.png)
![image](https://user-images.githubusercontent.com/8233283/29455259-1759df22-8443-11e7-916e-2e0c077a9f45.png)
